{% set version = "1.6.0rc1" %}

package:
    name: bluesky
    version: {{ version }}

source:
    git_url: https://github.com/nsls-ii/bluesky
    git_rev: v{{ version }}

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    skip: True  # [py2k]

requirements:
    build:
        - python
        - pip
    run:
        - cycler
        - databroker
        - event-model >=1.10.0
        - historydict
        - ipython
        - lmfit
        - matplotlib
        - numpy
        - ophyd
        - python
        - pyzmq
        - super_state_machine
        - toolz
        - tqdm

test:
    imports:
        - bluesky

about:
    home: https://github.com/bluesky/bluesky
    license: BSD
